In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#universal function, is functions which can be applied for each value
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
#take exponencial for each value
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [9]:
#create random array and call randn normal distribution

A = np.random.randn(10)

A

array([-1.09837303,  2.07625626,  1.61348567,  2.87850123, -0.93114747,
        0.09420691, -0.35685384, -0.37415307, -0.6656057 ,  0.90854345])

In [10]:
B = np.random.randn(10)
B

array([  1.98207417e+00,   7.83318546e-02,  -9.63779483e-02,
         1.73546992e+00,   7.41952149e-04,   2.58971680e-01,
         3.28315409e-01,  -3.87013806e-01,   1.51444933e+00,
         8.71353467e-01])

In [12]:
#Binary Function - functions which use two arrays

np.add(A,B)

array([ 0.88370113,  2.15458812,  1.51710772,  4.61397115, -0.93040552,
        0.35317859, -0.02853843, -0.76116688,  0.84884363,  1.77989692])

In [16]:
#find max between two arrays (compare value at both index)
np.maximum(A,B)

array([  1.98207417e+00,   2.07625626e+00,   1.61348567e+00,
         2.87850123e+00,   7.41952149e-04,   2.58971680e-01,
         3.28315409e-01,  -3.74153073e-01,   1.51444933e+00,
         9.08543449e-01])

In [17]:
#alla vailable math operations on numpy
website = 'https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True