In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
#save
np.save('myarray',arr)

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#laod saved file
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#save multiple arrays (ziped arrays)

np.savez('ziparray.npz', x = arr1, y = arr2 )

In [11]:
archive_array = np.load('ziparray.npz')

In [12]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [13]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#save and laod txt file

arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#txt file need to have delimiter, as a separater
np.savetxt('mytextarray.txt', arr, delimiter = ',')

In [17]:
#laod txt file
arr = np.loadtxt('mytextarray.txt', delimiter = ',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])